namespace SpriteKind {
    export const flame = SpriteKind.create()
    export const StatusBar = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (lvl >= 4) {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . 9 9 9 9 9 9 9 . . . . . 
            . . . 9 9 9 9 9 9 9 9 9 . . . . 
            . . . 9 9 9 9 9 9 9 9 9 . . . . 
            . . . 9 9 9 5 9 9 5 9 9 . . . . 
            . . . 9 9 9 9 9 9 9 9 9 . . . . 
            . . . 9 9 9 9 5 9 9 9 9 . . . . 
            . . . 9 9 9 9 9 9 9 9 9 . . . . 
            . . . 9 9 9 9 9 9 9 9 9 . . . . 
            . . . . 9 9 9 9 9 9 9 . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, ship, 0, -100)
        projectile.setKind(SpriteKind.Projectile)
    }
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    sprites.destroy(sprite, effects.fire, 500)
    lvl += -1
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    pause(500)
    info.changeLifeBy(-1)
})
let projectile: Sprite = null
let meteor: Sprite = null
let ship: Sprite = null
let lvl = 0
info.setLife(3)
lvl = 0
let fire = sprites.create(img`
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    2455555555554422
    2455555555554442
    2455555555554442
    2255555555555442
    2245555555555442
    2245555555555442
    2244555555555422
    2224455555555422
    222445555555542.
    .224455545555422
    .224455445555422
    .224444224555422
    .22222222444442.
    .22222222244442.
    ..2222...24422..
    ..222....22222..
    ................
    `, SpriteKind.flame)
ship = sprites.create(img`
    ................
    .......cd.......
    .......cb.......
    .......ff.......
    .......c2.......
    .......ff.......
    .......e2.......
    ......ee4e......
    ......e24e......
    .....ccceee.....
    ....ee2224ee....
    ..cfffcceeffee..
    .ccccee222242ee.
    ccccccee222422ee
    ccccccee222422ee
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    `, SpriteKind.Player)
fire.follow(ship, 100)
controller.moveSprite(ship)
controller.moveSprite(fire)
ship.setFlag(SpriteFlag.StayInScreen, true)
ship.setFlag(SpriteFlag.GhostThroughWalls, true)
effects.starField.startScreenEffect()
for (let index = 0; index < 100; index++) {
    pause(5000)
    pause(5000)
    lvl += 1
    meteor = sprites.create(img`
        . . . . . . . . c c c c . . . . 
        . . . . c c c c c c c c c . . . 
        . . . c f c c a a a a c a c . . 
        . . c c f f f f a a a c a a c . 
        . . c c a f f c a a f f f a a c 
        . . c c a a a a b c f f f a a c 
        . c c c c a c c b a f c a a c c 
        c a f f c c c a b b 6 b b b c c 
        c a f f f f c c c 6 b b b a a c 
        c a a c f f c a 6 6 b b b a a c 
        c c b a a a a b 6 b b a b b a . 
        . c c b b b b b b b a c c b a . 
        . . c c c b c c c b a a b c . . 
        . . . . c b a c c b b b c . . . 
        . . . . c b b a a 6 b c . . . . 
        . . . . . . b 6 6 c c . . . . . 
        `, SpriteKind.Enemy)
    meteor.setFlag(SpriteFlag.BounceOnWall, true)
    meteor.setVelocity(60, 60)
}
if (lvl > 3) {
    lvl = 4
}
